# Generated by Django 4.2.6 on 2023-10-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='postm',
        ),
    ]
