# Generated by Django 4.2.6 on 2023-10-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0002_rename_post_postm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postm',
            new_name='post',
        ),
    ]
